version: '3'

services:
  discord-bot:
    build: .
    container_name: discord-verification-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - USE_MOCK_MODE=false
    networks:
      - bot-network

  web-only:
    build: .
    container_name: discord-verification-web
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - USE_MOCK_MODE=true
      - PORT=3001
    command: node src/web-only.js
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge